### ISSUE TITLE
Inconsistent casing for trait SET7_SpellThief and trait under Zoe

### ISSUE THREAD

**Issue by 2471186676** [aaronlam1004/tft-set6-gadget-gizmos-api#1]
![trait](https://user-images.githubusercontent.com/57126889/174246573-16be4b74-ea39-47ea-b304-472e79c44ef2.png)
![zoe](https://user-images.githubusercontent.com/57126889/174246596-6e0f4f91-e704-40b9-b6f7-c692d3530d65.png)

**Comment by aaronlam1004** [comment]
Thanks for bringing this up! Just fixed it. 😄
